# Path relative to makefile
DATA_DIR := ./assets/pandoc/

# Path relative to data_dir
SCRIPTS_DIR := $(DATA_DIR)/scripts/
INDEX_METADATA := ${DATA_DIR}/metadata/index.json
HTML_WRITER := ${DATA_DIR}/filters/separate-alt-figcaption.lua
DATE_WRITER := ${DATA_DIR}/filters/last-updated.lua
CODEBLOCK_WRITER := ${DATA_DIR}/filters/codeblock-lang-attr.lua
ARTICLE_TEMPLATE := ${DATA_DIR}/templates/article-template.html

# Common options
PANDOC_OPTIONS = --standalone \
	--table-of-contents \
	--toc-depth=4 \
	--section-divs \
	--number-sections \
	--data-dir=$(DATA_DIR) \
	--template=$(ARTICLE_TEMPLATE) \
	--metadata-file=${INDEX_METADATA} \
	--lua-filter=$(DATE_WRITER) \
	--lua-filter=$(CODEBLOCK_WRITER) \
	--to $(HTML_WRITER)
TREE_OPTIONS = --noreport \
							 -d \
							 -f \
							 -J 
