# Path relative to makefile
DATA_DIR := ./assets/pandoc/
SCRIPTS_DIR := $(DATA_DIR)/scripts/

# Path relative to data_dir
INDEX_METADATA := ./metadata/index.json
HTML_WRITER := ./filters/separate-alt-figcaption.lua
DATE_WRITER := ./filters/last-updated.lua
CODEBLOCK_WRITER := ./filters/codeblock-lang-attr.lua
ARTICLE_TEMPLATE := ./templates/article-template.html

# Common options
PANDOC_OPTIONS = --standalone \
	--table-of-contents \
	--toc-depth=4 \
	--section-divs \
	--number-sections \
	--data-dir=$(DATA_DIR) \
	--template=$(ARTICLE_TEMPLATE)
	--lua-filter=$(DATE_WRITER) \
	--lua-filter=$(CODEBLOCK_WRITER) \
	--css $(SITE_STYLE) \
	--to $(HTML_WRITER)
TREE_OPTIONS = -I "_*" \
							 -L 2 \
							 --noreport \
							 -d \
							 -f \
							 -J 
