#!/usr/bin/env bash

TREE_OPTS=( --noreport --charset="utf-8" --metafirst --filesfirst)

dirname=$1

find "./$dirname" -mindepth 1 -maxdepth 1 -type d -print0 | 
  while IFS= read -r -d '' dir; do 
    tree -H "../../$dir" \
         "${TREE_OPTS[@]}" \
         -T "$(basename "$dir")" \
         -o "./assets/listings/${dirname}/${dir}-listing.html" \
         --hintro=/dev/null \
         --houtro=/dev/null \
         "$dir"
  done
