-- Problem:
--    The CSS class generated by ```lang is insufficient for specifying a general style rule that should be default ()
--
-- Solution:
--    Copy that class name to an attribute (data-language)

local pandoc_Pipe = (require("pandoc")).pipe
local languages = pandoc_Pipe("pandoc", { "--list-highlight-languages" }, "")

function CodeBlock(codeBlock)
  local classes = codeBlock.classes
  if classes then
    for _, class in pairs(classes) do
      if string.find(languages, class) then
        codeBlock.attributes.language = class
      end
    end
  end
  return codeBlock
end
